version: "3.9"
services:
  backend:
    image: dtuait/pwned-proxy-app-main:python-3.13-bullseye-django-5.1.6-myversion-1.0.2
    env_file:
      - ./pwned-proxy-backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    image: dtuait/nextjs-devcontainer-app-main:nodejs22-1.0.0
    env_file:
      - ./pwned-proxy-frontend/app-main/.env.local
    depends_on:
      - backend
    ports:
      - "3000:3000"
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
