name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate environment file
        run: ./generate_env.sh
      - name: Build images
        run: docker compose build
      - name: Run integration tests
        run: |
          docker compose up -d db
          docker compose run --rm app /usr/src/venvs/app-main/bin/python manage.py test
      - name: Shutdown
        if: always()
        run: docker compose down -v
