services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${LOCAL_UID:-1000}
        USER_GID: ${LOCAL_GID:-1000}
    volumes:
      - ../:/usr/src/project
    working_dir: /usr/src/project
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - PYTHONPATH=/usr/src/project
      - POSTGRES_HOST=dev-db
      - POSTGRES_DB=dev-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - dev-db
    networks:
      - devnet
    stdin_open: true
    tty: true
    command: sleep infinity

  dev-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=dev-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - de:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - devnet

volumes:
  de:

networks:
  devnet:
